/* Helpful, low-friction discovery and custom-case review features. */
['ui-polish.css','form-polish.css'].forEach(href=>{const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href=href;document.head.append(sheet)});const catalogFlow=document.createElement('script');catalogFlow.src='load-more.js';document.head.append(catalogFlow);
window.addEventListener('load',()=>{
  const PHONE_SUGGESTIONS={Samsung:['Galaxy A15','Galaxy S24','Galaxy S25 Ultra','Galaxy M35'],Redmi:['Redmi Note 14','Redmi Note 13','Redmi 13'],Xiaomi:['Xiaomi 14','Xiaomi 14 Civi'],POCO:['POCO X7','POCO X6','POCO M6'],Realme:['Realme 13','Realme C67'],Vivo:['Vivo Y29','Vivo Y200'],OPPO:['OPPO K12x','OPPO A58'],Motorola:['Moto G84','Moto G64'],OnePlus:['OnePlus Nord 4','OnePlus 13R'],'Google Pixel':['Pixel 9','Pixel 9a','Pixel 8a'],'Apple iPhone':['iPhone 16','iPhone 16 Pro','iPhone 15','iPhone 15 Pro']};
  const saveKey='coverlySavedDesignsV2',recentKey='coverlyRecentDesignsV2';
  const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(_){return[]}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  // Store a sheet design ID rather than a temporary on-page position. Positions
  // change whenever designs are added, removed, or reordered in the spreadsheet.
  const addRecent=id=>{const design=products.find(p=>String(p.id)===String(id));if(!design)return;const key=String(design.designId||design.id);write(recentKey,[key,...read(recentKey).filter(x=>String(x)!==key)].slice(0,6))};
  const originalZoom=window.showDesignImage;
  window.showDesignImage=id=>{addRecent(id);if(originalZoom)originalZoom(id)};
  window.toggleSavedDesign=id=>{const design=products.find(p=>String(p.id)===String(id));if(!design)return;const key=String(design.designId||design.id),saved=read(saveKey),next=saved.includes(key)?saved.filter(x=>x!==key):[...saved,key];write(saveKey,next);renderDiscovery()};
  function renderDiscovery(){const host=document.getElementById('discoveryShelf');if(!host)return;const saved=read(saveKey),recent=read(recentKey),find=id=>products.find(p=>String(p.designId||p.id)===String(id)),card=(p,label)=>p?`<button class="mini-design" onclick="showDesignImage(${p.id})"><span>${label}</span><b>${p.n}</b><small>${p.brand}</small></button>`:'',group=(label,items,tag)=>{const cards=items.map(find).filter(Boolean).map(p=>card(p,tag)).join('');return cards?`<section class="discovery-group"><p>${label}</p><div class="mini-designs">${cards}</div></section>`:''};host.innerHTML=`<div class="discovery-row">${group('Saved designs',saved,'♥ Saved')}${group('Recently viewed',recent,'↗ Viewed')}</div>`}
  const previousRender=window.renderProducts;
  window.renderProducts=()=>{previousRender();document.querySelectorAll('.design-card').forEach((card,index)=>{const design=products.filter(p=>(document.getElementById('modelFilter').value==='All'||p.brand===document.getElementById('modelFilter').value)&&`${p.n} ${p.brand} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(document.getElementById('search').value.toLowerCase()))[index];if(!design)return;const button=document.createElement('button');button.className='save-design';button.type='button';button.setAttribute('aria-label','Save '+design.n);button.textContent=read(saveKey).includes(String(design.designId||design.id))?'♥':'♡';button.onclick=event=>{event.stopPropagation();toggleSavedDesign(design.id)};card.querySelector('.image').append(button)});renderDiscovery()};
  document.querySelector('#shop').insertAdjacentHTML('beforeend','<div id="discoveryShelf"></div>');window.renderProducts();
  const originalStart=window.startCustom;
  window.startCustom=id=>{originalStart(id);setTimeout(()=>{const sheet=document.querySelector('.custom-sheet'),input=document.getElementById('customModel'),brand=document.getElementById('customBrand');if(!input||!brand)return;sheet.querySelector('.eyebrow')?.insertAdjacentHTML('afterend','<div class="builder-progress"><span class="active">1. Phone</span><span>2. Personalise</span><span>3. Review</span></div>');input.insertAdjacentHTML('afterend','<button type="button" class="model-help-button">Not sure? Find your model</button><div class="model-help-popover">On Android: Settings → About phone. On iPhone: Settings → General → About → Model Name.</div>');sheet.querySelector('.model-help-button').onclick=()=>sheet.querySelector('.model-help-popover').classList.toggle('show');let list=document.getElementById('phoneSuggestions');if(!list){list=document.createElement('datalist');list.id='phoneSuggestions';document.body.append(list)}const fill=()=>{list.innerHTML=(PHONE_SUGGESTIONS[brand.value]||[]).map(x=>`<option value="${x}">`).join('');input.setAttribute('list','phoneSuggestions')};brand.addEventListener('change',fill);fill();const add=document.getElementById('addCustom');const originalAdd=add.onclick;add.onclick=()=>{if(!input.value.trim()||!document.getElementById('modelConfirm').checked){originalAdd();return}sheet.querySelectorAll('.builder-progress span').forEach((x,i)=>x.classList.toggle('active',i===2));const review=document.createElement('div');review.className='case-review';review.innerHTML=`<b>Ready to make your case?</b><span>${brand.value} ${input.value.trim()}</span><small>Double-check your model. Production starts after order review.</small><div><button class="review-back">Edit</button><button class="review-confirm">Confirm & add</button></div>`;add.replaceWith(review);review.querySelector('.review-back').onclick=()=>{sheet.querySelectorAll('.builder-progress span').forEach((x,i)=>x.classList.toggle('active',i===0));review.replaceWith(add)};review.querySelector('.review-confirm').onclick=()=>{review.replaceWith(add);originalAdd()}}},0)};
  document.querySelector('.promo')?.insertAdjacentHTML('beforebegin','<section class="trust-strip"><div><b>Made for your model</b><span>Android + iPhone</span></div><div><b>Quality checked</b><span>Before dispatch</span></div><div><b>Pay your way</b><span>10% UPI off · ₹199 COD advance</span></div><div><b>Custom production</b><span>Processing: 1-2 Days </span></div></section>');
});
