// Edit prices here. Values are in INR. Leave discounted null for full-price items.
// Keys must exactly match the product title shown in the catalogue.
window.coverPriceOverrides = {
  'iPhone 17 Pro Max TechWoven Case with MagSafe - Green': { original: 5900, discounted: 899 },
  'iPhone 17 Pro TechWoven Case with MagSafe - Sienna': { original: 5900, discounted: 899 },
  'iPhone 17 Pro Max Silicone Case with MagSafe – Orange': { original: 4900, discounted: 799 },
  'iPhone 17 Pro Silicone Case with MagSafe – Midnight': { original: 4900, discounted: 799 },
  'iPhone 17 Pro Max Clear Case with MagSafe': { original: 4900, discounted: 799 },
  'Beats iPhone 17 Pro Max Rugged Case with MagSafe and Camera Control – Sierra Orange': { original: 7900, discounted: 1099 },
  'Beats iPhone 17 Pro Rugged Case with MagSafe and Camera Control – Rocky Blue': { original: 7900, discounted: 1099 },
  'Beats iPhone 17 Pro Max Kickstand Case with MagSafe and Camera Control – Pebble Pink': { original: 5900, discounted: 899 },
  'Beats iPhone 17 Pro Kickstand Case with MagSafe and Camera Control – Lime Stone': { original: 5900, discounted: 899 },
  'Beats iPhone 17 Pro Max Case with MagSafe and Camera Control — Granite Grey': { original: 4500, discounted: 699 },
  'Beats iPhone 17 Pro Case with MagSafe and Camera Control — Bedrock Blue': { original: 4500, discounted: 699 },
  'iPhone 17 Silicone Case with MagSafe – Electric Lavender': { original: 4900, discounted: 799 },
  'Beats iPhone 17 Rugged Case with MagSafe and Camera Control – Rocky Blue': { original: 7900, discounted: 1099 },
  'Beats iPhone 17 Kickstand Case with MagSafe and Camera Control – Lime Stone': { original: 5900, discounted: 899 },
  'Beats iPhone 17 Case with MagSafe and Camera Control — Pebble Pink': { original: 4500, discounted: 699 },
  'iPhone Air Case with MagSafe – Shadow': { original: 4900, discounted: 699 },
  'iPhone Air Bumper - Light Blue': { original: 3900, discounted: 599 },
  'Beats iPhone Air Case with MagSafe and Camera Control — Pebble Pink': { original: 4500, discounted: 699 },
  'iPhone 17e Silicone Case with MagSafe – Soft Pink': { original: 4900, discounted: 799 },
  'iPhone 17e Clear Case with MagSafe': { original: 4900, discounted: 799 },
  'Beats iPhone 17e Case with MagSafe – Bedrock Blue': { original: 4500, discounted: 799 },
  'iPhone 14 Plus Silicone Case with MagSafe – Chalk Pink': { original: 4900, discounted: 799 },
  'iPhone 14 Plus Clear Case with MagSafe': { original: 4900, discounted: 799 },
  'iPhone 14 Silicone Case with MagSafe – Chalk Pink': { original: 4900, discounted: 799 },
  'iPhone 15 Plus Silicone Case with MagSafe – Storm Blue': { original: 4900, discounted: 799 },
  'iPhone 15 Silicone Case with MagSafe – Storm Blue': { original: 4900, discounted: 799 },
  'iPhone 15 Clear Case with MagSafe': { original: 4900, discounted: 799 },
  'iPhone 16 Plus Silicone Case with MagSafe – Ultramarine': { original: 4900, discounted: 799 },
  'iPhone 16 Pro Max Silicone Case with MagSafe – Stone Grey': { original: 4900, discounted: 799 },
  'iPhone 16 Pro Silicone Case with MagSafe – Star Fruit': { original: 4900, discounted: 799 },
  'iPhone 16e Silicone Case – Neon Yellow': { original: 3900, discounted: 599 },
  'iPhone 16 Silicone Case with MagSafe – Ultramarine': { original: 4900, discounted: 799 },
  'iPhone 16 Clear Case with MagSafe': { original: 4900, discounted: 799 },
  'Beats iPhone 16 Case with MagSafe – Sunset Purple': { original: 4900, discounted: 799 },
  'Beats iPhone 16 Pro Case with MagSafe – Midnight Black': { original: 4900, discounted: 799 },
  'Beats iPhone 16 Pro Max Case with MagSafe – Midnight Black': { original: 4900, discounted: 799 },
  'Beats iPhone 16 Plus Case with MagSafe – Midnight Black': { original: 4900, discounted: 799 },
  'iPhone 15 Pro Max Silicone Case with MagSafe – Storm Blue': { original: 4900, discounted: 799 }
};

