const SPREADSHEET_ID='1vFyERjcp02kqyxLi4GNxpLftu8WXHXpuy1m_y3wVIrM';
const ORDER_HEADERS=['Order ID','Date','Customer Name','Phone','Email','Address','City','State','Pincode','Design ID','Design Name','Collection','Phone Brand','Phone Model','Customization Type','Customization Request','Personal Text','Reference Image','Customer Notes','Items','Subtotal','Discount','Total','Payment Method','Amount Paid','Amount Remaining','UTR','Payment Status','Order Status','Design Review','Production Status','Courier','Tracking URL'];
const DESIGN_HEADERS=['Design ID','Name','Collection','Price','Old Price','Image URL','Description','Tags','Active'];
function output(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON)}
function getSheet(name,headers){const ss=SPREADSHEET_ID?SpreadsheetApp.openById(SPREADSHEET_ID):SpreadsheetApp.getActive();const sh=ss.getSheetByName(name)||ss.insertSheet(name);if(!sh.getLastRow())sh.appendRow(headers);else{const current=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];headers.forEach((header,index)=>{if(current[index]!==header)sh.getRange(1,index+1).setValue(header)})}return sh}
function setupCoverlySheets(){getSheet('Orders',ORDER_HEADERS);getSheet('Designs',DESIGN_HEADERS)}
function readDesigns(){const rows=getSheet('Designs',DESIGN_HEADERS).getDataRange().getValues();if(rows.length<2)return[];const head=rows.shift(),col=key=>head.indexOf(key);return rows.filter(row=>String(row[col('Active')]).toLowerCase()!=='false'&&row[col('Name')]).map(row=>({id:String(row[col('Design ID')]||''),name:String(row[col('Name')]),collection:String(row[col('Collection')]),price:Number(row[col('Price')])||499,oldPrice:Number(row[col('Old Price')])||null,image:String(row[col('Image URL')]||''),description:String(row[col('Description')]||''),tags:String(row[col('Tags')]||'').split(',').map(x=>x.trim()).filter(Boolean)}))}
function saveOrder(order){const sh=getSheet('Orders',ORDER_HEADERS),ids=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1).getValues().flat():[];if(ids.includes(order.orderId))return{ok:true,duplicate:true};const items=order.items||[],first=items[0]||{},itemText=items.map(i=>`${i.designName||i.title||i.model||''} | ${i.phoneBrand||''} ${i.phoneModel||''} | qty ${i.quantity||1}`).join(' ; ');sh.appendRow([order.orderId,order.createdAt||new Date(),order.customerName||order.customer?.name||'',order.phone||order.customer?.phone||'',order.email||order.customer?.email||'',order.address||order.customer?.address||'',order.city||order.customer?.city||'',order.state||order.customer?.state||'',order.pincode||order.customer?.pincode||'',first.designId||order.designId||'',first.designName||order.designName||'',first.collection||order.collection||'',first.phoneBrand||order.phoneBrand||'',first.phoneModel||order.phoneModel||'',first.customizationType||order.customizationType||'',first.customizationRequest||order.customizationRequest||'',first.personalText||order.personalText||'',first.referenceImage||order.referenceImage||'',first.customerNotes||order.customerNotes||'',itemText,Number(order.subtotal||order.total||0),Number(order.discount||0),Number(order.total||0),order.paymentMethod||'',Number(order.amountPaid||order.total||0),Number(order.amountRemaining||0),order.utr||'',order.paymentStatus||'',order.orderStatus||'Order Placed','Pending','Order Placed','','']);return{ok:true}}
function parse(e){let raw=e&&e.postData&&e.postData.contents||e&&e.parameter&&e.parameter.payload||'{}';try{return JSON.parse(raw)}catch(_){return JSON.parse(decodeURIComponent(raw.replace(/^payload=/,'')))}}
function doPost(e){try{return output(saveOrder(parse(e)))}catch(err){return output({ok:false,error:String(err)})}}
function doGet(e){try{if((e.parameter.action||'')==='designs')return output({ok:true,designs:readDesigns()});const id=(e.parameter.orderId||'').trim(),phone=(e.parameter.phone||'').replace(/\D/g,'');if(!id||!phone)return output({ok:true,service:'Coverly order capture'});const rows=getSheet('Orders',ORDER_HEADERS).getDataRange().getValues();rows.shift();const record=rows.find(r=>String(r[0]).toLowerCase()===id.toLowerCase()&&String(r[3]).replace(/\D/g,'')===phone);return record?output({ok:true,found:true,orderId:record[0],paymentStatus:record[27],orderStatus:record[28]}):output({ok:false,found:false})}catch(err){return output({ok:false,error:String(err)})}}
